name: Waka Readme

on:
  schedule:
    # Runs every day 1am
    - cron: '0 1 * * *'
  workflow_dispatch:
  
jobs:
  update-readme:
    name: Update status
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_SHORT_INFO: "True"
          SHOW_LINES_OF_CODE: "True"
          SHOW_PROFILE_VIEWS: "True"
          SHOW_COMMIT: "True"
          SHOW_LANGUAGE: "True"
          SHOW_LANGUAGE_PER_REPO: "True"
          SHOW_TIMEZONE: "True"